// apariencia del mismo objeto para mantener coherencia visual.
import { StyleSheet } from "react-native";
import type { ThemeColors } from "./theme";

export function getStyles(colors: ThemeColors, colorCardSize: number, chartCardSize: number, glowCardSize: number, bottomPad = 0) {
  const cardBg = colors.primary + "12";

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: { flex: 1 },
    content: {
      padding: 16,
      paddingBottom: 16 + bottomPad,
    },
    profileSection: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      marginBottom: 24,
      padding: 14,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    profileField: { flex: 1, minWidth: 0 },
    profileFieldDisplay: { paddingRight: 34 },
    profileFieldEditing: { paddingRight: 0 },
    profileBigName: {
      fontSize: 22,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    profileSub: {
      marginTop: 3,
      fontSize: 11.5,
      color: colors.textSecondary,
    },
    nameEditBtn: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary + "14",
      alignItems: "center",
      justifyContent: "center",
    },
    profileLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 6,
    },
    nameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    nameInput: {
      flex: 1,
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      fontSize: 14,
      color: colors.textPrimary,
    },
    nameSaveBtn: {
      width: 38,
      height: 38,
      borderRadius: 10,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    nameSaveBtnDisabled: { opacity: 0.4 },
    section: { marginTop: 24 },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 8,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    rowIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
    },
    rowText: { flex: 1, gap: 2, minWidth: 0 },
    rowLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    rowSub: {
      fontSize: 10.5,
      color: colors.textSecondary,
    },
    rowItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    rowDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginLeft: 58,
    },
    syncCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    syncHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 12,
    },
    syncHeaderText: { flex: 1, gap: 5, minWidth: 0 },
    syncBody: { marginTop: 8 },
    syncStatusPill: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderRadius: 999,
      borderWidth: 1,
      paddingVertical: 2.5,
      paddingHorizontal: 8,
    },
    syncStatusDot: { width: 6, height: 6, borderRadius: 3 },
    syncStatusText: { fontSize: 9.5, fontWeight: "600" },
    dangerCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.error + "45",
      padding: 12,
    },
    dangerCardIcon: { backgroundColor: colors.error + "18" },
    dangerCardTitle: { fontSize: 13, fontWeight: "700", color: colors.error },
    dangerCardSub: { fontSize: 10.5, color: colors.textSecondary },
    themeSelector: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 3,
      gap: 3,
      marginBottom: 12,
    },
    themeOption: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 9,
      borderRadius: 9,
      gap: 4,
    },
    themeOptionActive: { backgroundColor: colors.primary },
    themeOptionText: {
      fontSize: 11,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    themeOptionTextActive: { color: colors.surface },

    newCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
    },
    newCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      padding: 14,
    },
    newCardIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.primary + "15",
      alignItems: "center",
      justifyContent: "center",
    },
    newCardTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    newCardDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginHorizontal: 14,
    },
    newCardList: {
      paddingHorizontal: 14,
      paddingBottom: 6,
    },
    newCardRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    newCardRowIcon: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    newCardCell: {
      flex: 1,
      gap: 2,
    },
    newCardCellFull: {
      flex: 0,
      width: "100%",
    },
    newCardInline: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    newCardLabel: {
      flex: 1,
      fontSize: 13.5,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    newCardValue: {
      fontSize: 13.5,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    colorDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },

    // Tienda modal
    // Capa transparente: deja ver el BackgroundDecor del contenedor.
    shopSafe: {
      flex: 1,
    },
    shopContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    shopHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
      gap: 14,
    },
    shopBackBtn: {
      padding: 4,
    },
    shopTitle: {
      fontSize: 19,
      fontWeight: "800",
      color: colors.textPrimary,
    },
    accordionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.surface + "CC",
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    accordionLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    accordionInfo: {
      gap: 1,
      flex: 1,
    },
    accordionTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    accordionDesc: {
      fontSize: 11,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    accordionSub: {
      fontSize: 10,
      fontWeight: "400",
      color: colors.textSecondary,
      opacity: 0.7,
      marginTop: 1,
    },
    freeKoinsCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginHorizontal: 12,
      marginTop: 12,
      backgroundColor: colors.surface + "CC",
      borderWidth: 1,
      borderColor: colors.primary + "55",
      borderRadius: 12,
    },
    freeKoinsInfo: {
      flex: 1,
      gap: 2,
    },
    freeKoinsTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.primary,
    },
    freeKoinsDesc: {
      fontSize: 11,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    accordionDecor: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      pointerEvents: "none",
    },
    shopScroll: {
      paddingBottom: 40,
    },
    shopPointsBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 20,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    shopPointsText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.warning,
    },
    comboCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginHorizontal: 16,
      marginTop: 10,
      marginBottom: 20,
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
    },
    comboInfo: {
      flex: 1,
      gap: 2,
    },
    comboTitle: {
      fontSize: 13,
      fontWeight: "700",
    },
    comboDesc: {
      fontSize: 10,
      lineHeight: 14,
    },
    comboTotal: {
      fontSize: 12,
      fontWeight: "700",
      marginTop: 2,
    },
    comboShuffle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    recomContainer: {
      paddingHorizontal: 12,
      paddingTop: 8,
      gap: 8,
      paddingBottom: 40,
    },
    recomCard: {
      borderRadius: 12,
      borderWidth: 1,
      padding: 10,
      gap: 8,
    },
    recomHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    recomPriceBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: colors.warning + "14",
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 8,
    },
    recomPriceBadgeText: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.warning,
    },
    recomActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      paddingTop: 2,
    },
    recomActionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 11,
    },
    recomActionText: {
      fontSize: 11,
      fontWeight: "700",
    },
    recomEquiping: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    recomEquipingText: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    recomChips: {
      flexDirection: "row",
      gap: 6,
    },
    recomChip: {
      flex: 1,
      alignItems: "center",
      gap: 3,
    },
    recomChipBox: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    recomChipDot: {
      width: 16,
      height: 16,
      borderRadius: 8,
    },
    recomChipDotTheme: {
      borderWidth: 2,
      borderColor: "rgba(255,255,255,0.35)",
    },
    recomChipBars: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 2,
    },
    recomChipName: {
      fontSize: 8,
      color: colors.textSecondary,
      textAlign: "center",
      maxWidth: "100%",
    },
    recomFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    recomLabel: {
      flex: 1,
      fontSize: 11,
      fontWeight: "700",
    },
    recomPrice: {
      fontSize: 12,
      fontWeight: "800",
    },
    recomComplete: {
      fontSize: 11,
      fontWeight: "700",
    },
    ptsOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
      padding: 24,
    },
    // Sheet inferior del modal de koins (estilo HintSheet)
    koinsOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(0,0,0,0.45)",
    },
    koinsSheet: {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderWidth: 1,
      borderBottomWidth: 0,
      padding: 20,
      paddingTop: 10,
      gap: 16,
    },
    koinsGrabber: {
      width: 36,
      height: 4,
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 10,
    },
    koinsScroll: {
      maxHeight: 380,
    },
    koinsIntro: {
      gap: 10,
    },
    koinsHero: {
      alignItems: "center",
      paddingTop: 4,
      paddingBottom: 2,
    },
    ptsCard: {
      width: "100%",
      maxWidth: 380,
      borderRadius: 16,
      borderWidth: 1,
      padding: 20,
      gap: 16,
    },
    ptsCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    ptsCardTitle: {
      fontSize: 17,
      fontWeight: "700",
      flex: 1,
    },
    ptsSection: {
      gap: 6,
    },
    ptsSectionTitle: {
      fontSize: 11,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    ptsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    ptsRowText: {
      flex: 1,
      fontSize: 13,
    },
    ptsRowValue: {
      fontSize: 13,
      fontWeight: "700",
    },
    ptsHelpText: {
      fontSize: 12.5,
      lineHeight: 18,
    },
    helpScroll: {
      gap: 16,
      paddingBottom: 4,
    },
    ptsBtn: {
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    ptsBtnText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#fff",
    },
    feedbackFab: {
      position: "absolute",
      bottom: 20,
      right: 20,
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    feedbackOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
      padding: 24,
    },
    feedbackCard: {
      width: "100%",
      maxWidth: 420,
      borderRadius: 14,
      borderWidth: 1,
      padding: 20,
      gap: 16,
    },
    feedbackHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    feedbackTitle: {
      fontSize: 17,
      fontWeight: "700",
    },
    feedbackInput: {
      borderRadius: 10,
      borderWidth: 1,
      padding: 12,
      fontSize: 14,
      minHeight: 100,
    },
    feedbackInfo: {
      fontSize: 12,
      lineHeight: 18,
      textAlign: "center",
    },
    feedbackBadgesContainer: {
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      gap: 8,
    },
    feedbackConfigLabel: {
      fontSize: 11,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    feedbackBadgesRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    feedbackBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      borderRadius: 10,
      borderWidth: 1,
      paddingVertical: 4,
      paddingHorizontal: 10,
      flexShrink: 0,
    },
    feedbackBadgeLabel: {
      fontSize: 10,
      fontWeight: "600",
    },
    feedbackBadgeValue: {
      fontSize: 11,
      fontWeight: "700",
    },
    feedbackActions: {
      flexDirection: "row",
      gap: 10,
    },
    feedbackBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "transparent",
    },
    feedbackBtnPrimary: {
      borderWidth: 0,
    },
    feedbackBtnText: {
      fontSize: 14,
      fontWeight: "600",
    },
    shopGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 40,
      gap: 8,
      justifyContent: "space-between",
    },
    shopCard: {
      backgroundColor: cardBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 10,
      gap: 6,
      alignItems: "center",
    },
    shopCardActive: {
      borderColor: colors.primary,
      borderWidth: 2,
    },
    shopCardLocked: {
      opacity: 0.5,
    },
    shopThemeSelector: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 2,
      gap: 2,
      marginHorizontal: 12,
      marginBottom: 14,
    },
    shopThemeOption: {
      flex: 1,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      paddingVertical: 6,
      borderRadius: 8,
      gap: 4,
    },
    shopThemeOptionActive: { backgroundColor: colors.primary },
    shopThemeOptionText: {
      fontSize: 11,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    shopThemeOptionTextActive: { color: colors.surface },
    swatchWrap: {
      position: "relative",
      alignItems: "center",
    },
    shopSwatches: {
      flexDirection: "row",
      width: 60,
      height: 60,
      borderRadius: 9,
      overflow: "hidden",
    },
    shopSwatch: {
      width: 12,
      height: 60,
    },
    lockOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 9,
      backgroundColor: "rgba(0,0,0,0.35)",
    },
    lockPriceText: {
      fontSize: 9,
      fontWeight: "800",
      color: colors.surface,
    },
    colorLockOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 5,
      backgroundColor: "transparent",
    },
    bgPreview: {
      width: 54,
      height: 54,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    colorGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 12,
      paddingTop: 8,
      gap: 6,
      paddingBottom: 40,
      justifyContent: "space-between",
    },
    colorCard: {
      width: colorCardSize,
      height: colorCardSize,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: "transparent",
      padding: 2,
    },
    colorCardActive: {
      borderColor: colors.primary,
    },
    chartCardWrap: {
      alignItems: "center",
      width: chartCardSize,
    },
    chartCard: {
      width: chartCardSize,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: "transparent",
      padding: 2,
      alignItems: "center",
    },
    colorSwatch: {
      flex: 1,
      borderRadius: 5,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    chartPairSwatch: {
      width: 44,
      height: 44,
      borderRadius: 5,
      overflow: "hidden",
      alignSelf: "center",
      alignItems: "center",
      justifyContent: "center",
      padding: 2,
    },
    chartPreviewCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      marginHorizontal: 12,
      marginTop: 8,
      marginBottom: 4,
      padding: 12,
    },
    chartPreviewArt: {
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    chartPreviewInfo: {
      gap: 2,
    },
    chartPreviewName: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    chartPreviewRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      marginTop: 4,
    },
    chartPreviewDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    chartPreviewHint: {
      fontSize: 11,
      color: colors.textSecondary,
      marginRight: 4,
    },
    chartDiagonalWrap: {
      position: "absolute",
      top: -10,
      left: -10,
      width: 64,
      height: 64,
      transform: [{ rotate: "-45deg" }],
    },
    chartCheckOverlay: {
      position: "absolute",
      top: 2,
      right: 2,
      backgroundColor: colors.primary,
      borderRadius: 8,
      width: 16,
      height: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    chartPairName: {
      fontSize: 9,
      color: colors.textSecondary,
      marginTop: 2,
      textAlign: "center",
      width: chartCardSize,
    },
    moveSwatch: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
    },
    glowGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 12,
      paddingTop: 8,
      gap: 6,
      paddingBottom: 12,
      justifyContent: "space-between",
    },
    glowCard: {
      width: glowCardSize,
      backgroundColor: cardBg,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 6,
      gap: 4,
      alignItems: "center",
    },
    glowCardActive: {
      borderColor: colors.primary,
      borderWidth: 2,
    },
    glowSwatchWrap: {
      position: "relative",
      alignItems: "center",
    },
    glowSwatch: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    glowSwatchRainbow: {
      width: 32,
      height: 32,
      borderRadius: 8,
      flexDirection: "row",
      overflow: "hidden",
    },
    rainbowStripe: {
      flex: 1,
    },
    glowCardName: {
      fontSize: 9,
      fontWeight: "600",
      color: colors.textPrimary,
      textAlign: "center",
    },
    intensitySection: {
      paddingHorizontal: 16,
      paddingBottom: 40,
      gap: 8,
    },
    intensityLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    intensityTrack: {
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.border + "50",
      overflow: "hidden",
      justifyContent: "center",
    },
    intensityFill: {
      height: "100%",
      borderRadius: 12,
      opacity: 0.6,
    },
    ColorBtnPreview: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    shopCardName: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textPrimary,
      textAlign: "center",
      alignSelf: "stretch",
    },
    group: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    input: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: colors.textPrimary,
      fontSize: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    inputLast: { borderBottomWidth: 0 },
    actionRow: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    actionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 12,
    },
    actionBtnGhost: { backgroundColor: "transparent" },
    actionBtnGhostText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: "600",
    },
    actionBtnPrimary: { backgroundColor: colors.primary },
    actionBtnPrimaryText: {
      color: colors.surface,
      fontSize: 13,
      fontWeight: "600",
    },
    actionBtnDisabled: { opacity: 0.6 },
    dangerBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
    },
    dangerText: {
      color: colors.error,
      fontSize: 13,
      fontWeight: "600",
    },
    deleteSheetOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    deleteSheet: {
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 32,
      gap: 6,
    },
    deleteSheetHandle: {
      alignSelf: "center",
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 10,
    },
    deleteSheetTitle: {
      fontSize: 16,
      fontWeight: "700",
    },
    deleteSheetSub: {
      fontSize: 12,
      marginBottom: 12,
    },
    deleteOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      borderRadius: 12,
      borderWidth: 1,
      padding: 12,
    },
    deleteOptionIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
    },
    deleteOptionInfo: {
      flex: 1,
      gap: 2,
    },
    deleteOptionTitle: {
      fontSize: 13,
      fontWeight: "700",
    },
    deleteOptionDesc: {
      fontSize: 11,
      lineHeight: 14,
    },
    deleteCancel: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      alignItems: "center",
      paddingVertical: 12,
    },
    deleteCancelText: {
      fontSize: 13,
      fontWeight: "600",
    },
    deleteListBody: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 24 + bottomPad,
      gap: 8,
    },
    deleteSummary: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderRadius: 12,
      borderWidth: 1,
      padding: 12,
      marginBottom: 4,
    },
    deleteSummaryText: {
      flex: 1,
      fontSize: 11,
      lineHeight: 15,
    },
    deleteRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      borderRadius: 10,
      borderWidth: 1,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    deleteRowIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
    },
    deleteRowLabel: {
      flex: 1,
      fontSize: 12,
    },
    deleteRowCount: {
      fontSize: 12,
      fontWeight: "700",
      minWidth: 24,
      textAlign: "right",
    },
    deleteFooter: {
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 26,
      borderTopWidth: 1,
    },
    deleteFooterBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      borderRadius: 12,
      borderWidth: 1,
      paddingVertical: 13,
    },
    deleteFooterBtnDanger: {
      borderWidth: 0,
    },
    deleteFooterBtnText: {
      fontSize: 14,
      fontWeight: "700",
    },
    deleteConfirmIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    deleteConfirmTitle: {
      fontSize: 17,
      fontWeight: "800",
      textAlign: "center",
      marginBottom: 8,
    },
    deleteConfirmDesc: {
      fontSize: 13,
      lineHeight: 18,
      textAlign: "center",
      marginBottom: 20,
    },
    deleteConfirmActions: {
      flexDirection: "row",
      gap: 10,
    },
    deleteConfirmBtn: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
    },
    deleteConfirmBtnText: {
      fontSize: 14,
      fontWeight: "700",
    },
    deleteProgressWrap: {
      alignSelf: "stretch",
      marginBottom: 20,
    },
    deleteProgressRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    deleteProgressLabel: {
      fontSize: 12,
      fontWeight: "600",
      flex: 1,
      marginRight: 8,
    },
    deleteProgressPct: {
      fontSize: 12,
      fontWeight: "700",
      fontVariant: ["tabular-nums"],
    },
    deleteProgressTrack: {
      height: 6,
      borderRadius: 3,
      overflow: "hidden",
    },
    deleteProgressFill: {
      height: "100%",
      borderRadius: 3,
    },
    deleteProgressCount: {
      fontSize: 11,
      marginTop: 6,
      textAlign: "center",
    },
    footerWrap: {
      paddingTop: 14,
      paddingBottom: 28 + bottomPad,
      paddingHorizontal: 16,
      backgroundColor: colors.background,
      position: "relative",
    },
    footerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    footer: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: "center",
      opacity: 0.6,
      letterSpacing: 0.3,
    },
    // Area invisible (derecha inferior del footer) que abre el menu de desarrollo.
    devTrigger: {
      position: "absolute",
      right: 10,
      bottom: 10,
      width: 64,
      height: 40,
      backgroundColor: "transparent",
    },
    codeCloseBtn: {
      position: "absolute",
      top: 10,
      right: 10,
      padding: 4,
      zIndex: 1,
    },
    rewardTopRow: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 8,
    },
    rewardBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 20,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    rewardBadgeText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.warning,
    },
    rewardText: {
      fontSize: 16,
      fontWeight: "600",
      lineHeight: 24,
      textAlign: "center",
      paddingVertical: 8,
    },
    rewardClaimBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
    rewardClaimText: {
      fontSize: 16,
      fontWeight: "700",
    },
    codeRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    codeInput: {
      width: 56,
      height: 56,
      borderRadius: 12,
      borderWidth: 1,
      textAlign: "center",
      fontSize: 20,
      fontWeight: "700",
    },
  });
}
